<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LP0041710" failures="1" tests="3" name="SDLC Login(failed)" time="44.128" errors="0" timestamp="2025-02-08T15:40:36 CST">
  <testcase classname="com.salesForce.Test.SDLCLoginTest" name="loginErrorMsg" time="5.97">
    <failure type="java.lang.AssertionError" message="expected [fPlease enter your password.] but found [Please enter your password.]">
      <![CDATA[java.lang.AssertionError: expected [fPlease enter your password.] but found [Please enter your password.]
at com.salesForce.Test.SDLCLoginTest.loginErrorMsg(SDLCLoginTest.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- loginErrorMsg -->
  <testcase classname="com.salesForce.Test.SDLCLoginTest" name="loginToSalesForce" time="6.675"/>
  <testcase classname="com.salesForce.Test.SDLCLoginTest" name="checkRememberMe" time="11.028"/>
  <testcase classname="com.salesForce.Test.SDLCLoginTest" name="inCorrectCredentialErrorMsg" time="0.0">
    <ignored/>
  </testcase> <!-- inCorrectCredentialErrorMsg -->
  <testcase classname="com.salesForce.Test.SDLCLoginTest" name="forgotPsw" time="0.0">
    <ignored/>
  </testcase> <!-- forgotPsw -->
</testsuite> <!-- SDLC Login(failed) -->
